### ISSUE TITLE
Not possible to view or update a profile.

### ISSUE THREAD

**Issue by terrameijar** [PyZim/pyconzim_website#24]
Steps to reproduce:
1. Visit http://zw.pycon.org/ , sign up for a new account and fill in all required details.
2. After signing up, login using credentials used in step 1.
3. Click the last link in the top navigation bar..i.e Hello <username> link. This link points to http://zw.pycon.org/profiles/home/

Expected results:
I am taken to a page that shows a summary of my profile including bio, gravatar picture and details.

Actual Results:
My gravatar image appears. No profile summary shown. There's a message on the page instead that says "You have not created a profile yet. Please click the button below to create your profile." with a link to create a new profile.
Clicking on the create profile link takes me back to http://zw.pycon.org/profiles/create_profile/

Re-completing the profile doesn't work. Filling in the profile details a second time and clicking "update profile" returns a 500 error. I assume that is because it isn't possible to overwrite profile data?

**Comment by terrameijar** [comment]
And in case this helps in any way, I use Firefox 55 on Ubuntu.

**Comment by hbutau** [comment]
@terrameijar fixed!
